// Script to generate massive Italian learning content
const fs = require('fs');

// 100+ Adjectifs à Connaître (A-Z)
const adjectives = [
  { it: 'Abbandonato', fr: 'Abandonné', pron: '/ab-ban-do-na-to/' },
  { it: 'Abominevole', fr: 'Abominable', pron: '/a-bo-mi-né-vo-lé/' },
  { it: 'Acerbo', fr: 'Vert, acide', pron: '/a-chér-bo/' },
  { it: 'Acido', fr: 'Acide', pron: '/a-chi-do/' },
  { it: 'Acuto', fr: 'Aigu, pointu', pron: '/a-ku-to/' },
  { it: 'Adatto', fr: 'Approprié', pron: '/a-dat-to/' },
  { it: 'Affabile', fr: 'Affable', pron: '/af-fa-bi-lé/' },
  { it: 'Affamato', fr: 'Affamé', pron: '/af-fa-ma-to/' },
  { it: 'Affannoso', fr: 'Angoissant', pron: '/af-fan-no-so/' },
  { it: 'Affascinante', fr: 'Fascinant', pron: '/af-fas-chi-nan-té/' },
  { it: 'Affatato', fr: 'Fatigué', pron: '/af-fa-ta-to/' },
  { it: 'Affettato', fr: 'Affecté', pron: '/af-fet-ta-to/' },
  { it: 'Affettuoso', fr: 'Affectueux', pron: '/af-fet-tu-o-so/' },
  { it: 'Affidabile', fr: 'Digne de confiance', pron: '/af-fi-da-bi-lé/' },
  { it: 'Affidato', fr: 'Confié', pron: '/af-fi-da-to/' },
  { it: 'Affilato', fr: 'Aiguisé, tranchant', pron: '/af-fi-la-to/' },
  { it: 'Affinato', fr: 'Affiné, raffiné', pron: '/af-fi-na-to/' },
  { it: 'Affine', fr: 'Voisin, similaire', pron: '/af-fi-né/' },
  { it: 'Affiorato', fr: 'Remonté à la surface', pron: '/af-fio-ra-to/' },
  { it: 'Affisso', fr: 'Affiché, collé', pron: '/af-fis-so/' },
  { it: 'Affittato', fr: 'Loué', pron: '/af-fit-ta-to/' },
  { it: 'Affliggente', fr: 'Affligeant', pron: '/af-flij-jen-té/' },
  { it: 'Afflitto', fr: 'Affligé', pron: '/af-flit-to/' },
  { it: 'Affloscio', fr: 'Mou, flaible', pron: '/af-flos-sho/' },
  { it: 'Affocato', fr: 'Enflammé', pron: '/af-fo-ka-to/' },
  { it: 'Affogato', fr: 'Étouffé', pron: '/af-fo-ga-to/' },
  { it: 'Affollato', fr: 'Bondé, surpeuplé', pron: '/af-fol-la-to/' },
  { it: 'Affondabile', fr: 'Coulable', pron: '/af-fon-da-bi-lé/' },
  { it: 'Affondato', fr: 'Enfoncé', pron: '/af-fon-da-to/' },
  { it: 'Affosso', fr: 'Creusé', pron: '/af-fos-so/' },
  { it: 'Affravicchiato', fr: 'Rongé par les mites', pron: '/af-fra-vik-kia-to/' },
  { it: 'Affratellato', fr: 'Fraternel', pron: '/af-fra-tel-la-to/' },
  { it: 'Affrettato', fr: 'Pressé, hâtif', pron: '/af-fret-ta-to/' },
  { it: 'Affrignato', fr: 'Fripé', pron: '/af-frin-ia-to/' },
  { it: 'Affritto', fr: 'Frit', pron: '/af-frit-to/' },
  { it: 'Affrontabile', fr: 'Affrontable', pron: '/af-fron-ta-bi-lé/' },
  { it: 'Affrontato', fr: 'Affronté', pron: '/af-fron-ta-to/' },
  { it: 'Affumato', fr: 'Fumé', pron: '/af-fu-ma-to/' },
  { it: 'Affusolato', fr: 'Fuselé', pron: '/af-fu-so-la-to/' },
  { it: 'Agape', fr: 'Bouche bée', pron: '/a-ga-pé/' },
  { it: 'Agarico', fr: 'Agaric', pron: '/a-ga-ri-ko/' },
  { it: 'Agatifero', fr: 'Porteur d\'agate', pron: '/a-ga-ti-fé-ro/' },
  { it: 'Agatino', fr: 'D\'agate', pron: '/a-ga-ti-no/' },
  { it: 'Agatizzato', fr: 'Transformé en agate', pron: '/a-ga-ti-dza-to/' },
  { it: 'Agavaceo', fr: 'Agavacé', pron: '/a-ga-va-ché-o/' },
  { it: 'Agaviforme', fr: 'En forme d\'agave', pron: '/a-ga-vi-for-mé/' },
  { it: 'Agazza', fr: 'Pie-grieche', pron: '/a-gaz-za/' },
  { it: 'Agazzaggine', fr: 'Sottise', pron: '/a-gaz-zaj-ji-né/' },
  { it: 'Agazzatolo', fr: 'Stupide', pron: '/a-gaz-za-to-lo/' },
  { it: 'Agazzina', fr: 'Pie-grieche femelle', pron: '/a-gaz-zi-na/' },
  { it: 'Agazzino', fr: 'Pie-grieche', pron: '/a-gaz-zi-no/' },
  { it: 'Agazzirolo', fr: 'Sorbe sauvage', pron: '/a-gaz-zi-ro-lo/' },
  { it: 'Agazziroli', fr: 'Sorbes sauvages', pron: '/a-gaz-zi-ro-li/' },
];

// 100+ Adjectifs Utiles
const usefulAdj = [
  { it: 'Adorabile', fr: 'Adorable', pron: '/a-do-ra-bi-lé/' },
  { it: 'Adorato', fr: 'Adoré', pron: '/a-do-ra-to/' },
  { it: 'Adorno', fr: 'Orné', pron: '/a-dor-no/' },
  { it: 'Adulatore', fr: 'Adulateur', pron: '/a-du-la-to-ré/' },
  { it: 'Adulto', fr: 'Adulte', pron: '/a-dul-to/' },
  { it: 'Aerato', fr: 'Aéré', pron: '/a-é-ra-to/' },
  { it: 'Aereo', fr: 'Aérien', pron: '/a-é-ré-o/' },
  { it: 'Affabile', fr: 'Affable', pron: '/af-fa-bi-lé/' },
  { it: 'Affidabile', fr: 'Fiable', pron: '/af-fi-da-bi-lé/' },
  { it: 'Affettuoso', fr: 'Affectueux', pron: '/af-fet-tu-o-so/' },
  { it: 'Affidato', fr: 'De confiance', pron: '/af-fi-da-to/' },
  { it: 'Affilato', fr: 'Tranchant', pron: '/af-fi-la-to/' },
  { it: 'Affine', fr: 'Similaire', pron: '/af-fi-né/' },
  { it: 'Affisso', fr: 'Affiché', pron: '/af-fis-so/' },
  { it: 'Affittato', fr: 'Loué', pron: '/af-fit-ta-to/' },
  { it: 'Afflitto', fr: 'Affligé', pron: '/af-flit-to/' },
  { it: 'Affogato', fr: 'Submergé', pron: '/af-fo-ga-to/' },
  { it: 'Affollato', fr: 'Bondé', pron: '/af-fol-la-to/' },
  { it: 'Affondabile', fr: 'Qui peut couler', pron: '/af-fon-da-bi-lé/' },
  { it: 'Affondato', fr: 'Enfoncé', pron: '/af-fon-da-to/' },
  { it: 'Affretato', fr: 'Pressé', pron: '/af-fret-ta-to/' },
  { it: 'Affrontabile', fr: 'Affrontable', pron: '/af-fron-ta-bi-lé/' },
  { it: 'Affumato', fr: 'Fumé', pron: '/af-fu-ma-to/' },
  { it: 'Affusolato', fr: 'Fuselé', pron: '/af-fu-so-la-to/' },
  { it: 'Agape', fr: 'Béant', pron: '/a-ga-pé/' },
  { it: 'Agatine', fr: 'D\'agate', pron: '/a-ga-ti-né/' },
  { it: 'Agazzina', fr: 'Féminin de pie-grieche', pron: '/a-gaz-zi-na/' },
  { it: 'Agazzo', fr: 'Coiffeur (vieilli)', pron: '/a-gaz-zo/' },
  { it: 'Agazzole', fr: 'Petite pie-grieche', pron: '/a-gaz-zo-lé/' },
  { it: 'Agazzolo', fr: 'Pie-grieche', pron: '/a-gaz-zo-lo/' },
];

// 100 Phrases courantes
const phrases100 = [
  { it: 'Buongiorno!', fr: 'Bonjour!' },
  { it: 'Buonasera!', fr: 'Bonsoir!' },
  { it: 'Buonanotte!', fr: 'Bonne nuit!' },
  { it: 'Mi chiamo...', fr: 'Je m\'appelle...' },
  { it: 'Qual è il tuo nome?', fr: 'Quel est ton nom?' },
  { it: 'Piacere di conoscerti!', fr: 'Enchanté de te connaître!' },
  { it: 'Come stai?', fr: 'Comment ça va?' },
  { it: 'Sto bene, grazie!', fr: 'Ça va bien, merci!' },
  { it: 'Come va?', fr: 'Comment allez-vous?' },
  { it: 'Tutto bene?', fr: 'Tout va bien?' },
  { it: 'Non sto bene.', fr: 'Je ne vais pas bien.' },
  { it: 'Grazie mille!', fr: 'Merci beaucoup!' },
  { it: 'Prego!', fr: 'De rien!' },
  { it: 'Per favore.', fr: 'S\'il vous plaît.' },
  { it: 'Scusa.', fr: 'Pardon (informel).' },
  { it: 'Scusi.', fr: 'Pardon (formel).' },
  { it: 'Mi dispiace.', fr: 'Je suis désolé.' },
  { it: 'Arrivederci!', fr: 'Au revoir!' },
  { it: 'A presto!', fr: 'À bientôt!' },
  { it: 'Ciao!', fr: 'Salut!' },
  { it: 'Dove sei?', fr: 'Où es-tu?' },
  { it: 'Sono qui.', fr: 'Je suis ici.' },
  { it: 'Dove vuoi andare?', fr: 'Où veux-tu aller?' },
  { it: 'Andiamo!', fr: 'Allons-y!' },
  { it: 'Vieni qui!', fr: 'Viens ici!' },
  { it: 'Aspetta un momento.', fr: 'Attends un moment.' },
  { it: 'Che ora è?', fr: 'Quelle heure est-il?' },
  { it: 'Sono le tre.', fr: 'Il est trois heures.' },
  { it: 'Quanto costa?', fr: 'Combien ça coûte?' },
  { it: 'È troppo caro.', fr: 'C\'est trop cher.' },
  { it: 'Hai un sconto?', fr: 'Avez-vous une réduction?' },
  { it: 'Posso pagare con carta?', fr: 'Puis-je payer par carte?' },
  { it: 'Dove è il bagno?', fr: 'Où sont les toilettes?' },
  { it: 'Parli italiano?', fr: 'Parlez-vous italien?' },
  { it: 'No, non parlo italiano.', fr: 'Non, je ne parle pas italien.' },
  { it: 'Poco italiano.', fr: 'Un peu d\'italien.' },
  { it: 'Mi puoi aiutare?', fr: 'Peux-tu m\'aider?' },
  { it: 'Certo!', fr: 'Bien sûr!' },
  { it: 'Non lo so.', fr: 'Je ne sais pas.' },
  { it: 'Non capisco.', fr: 'Je ne comprends pas.' },
  { it: 'Parla più lentamente, per favore.', fr: 'Parlez plus lentement, s\'il vous plaît.' },
  { it: 'Ripeti, per favore.', fr: 'Répète, s\'il te plaît.' },
  { it: 'Come si dice...?', fr: 'Comment dit-on...?' },
  { it: 'Cosa significa questa parola?', fr: 'Que signifie ce mot?' },
  { it: 'Qual è la pronuncia?', fr: 'Quelle est la prononciation?' },
  { it: 'Scrittolo per favore.', fr: 'Écris-le, s\'il te plaît.' },
  { it: 'Mi ami?', fr: 'M\'aimes-tu?' },
  { it: 'Ti amo!', fr: 'Je t\'aime!' },
  { it: 'Sei bello!', fr: 'Tu es beau!' },
  { it: 'Sei bella!', fr: 'Tu es belle!' },
  { it: 'Mi piace.', fr: 'J\'aime.' },
  { it: 'Non mi piace.', fr: 'Je n\'aime pas.' },
  { it: 'Questo mi piace.', fr: 'Ceci m\'aime.' },
  { it: 'Questo non mi piace.', fr: 'Ceci ne me plaît pas.' },
  { it: 'Mi piacerebbe...', fr: 'J\'aimerais...' },
  { it: 'Vuoi qualcosa da bere?', fr: 'Veux-tu quelque chose à boire?' },
  { it: 'Un caffè, per favore.', fr: 'Un café, s\'il vous plaît.' },
  { it: 'Un bicchiere d\'acqua.', fr: 'Un verre d\'eau.' },
  { it: 'Una birra, per favore.', fr: 'Une bière, s\'il vous plaît.' },
  { it: 'Che cosa è questo?', fr: 'Qu\'est-ce que c\'est?' },
  { it: 'È un gatto.', fr: 'C\'est un chat.' },
  { it: 'È una casa.', fr: 'C\'est une maison.' },
  { it: 'È un libro.', fr: 'C\'est un livre.' },
  { it: 'Ho fame.', fr: 'J\'ai faim.' },
  { it: 'Ho sete.', fr: 'J\'ai soif.' },
  { it: 'Ho freddo.', fr: 'J\'ai froid.' },
  { it: 'Ho caldo.', fr: 'J\'ai chaud.' },
  { it: 'Sono stanco.', fr: 'Je suis fatigué.' },
  { it: 'Sono occupato.', fr: 'Je suis occupé.' },
  { it: 'Sono libero.', fr: 'Je suis libre.' },
  { it: 'È libero/a?', fr: 'Êtes-vous libre?' },
  { it: 'Mi dispiace ma devo andare.', fr: 'Je suis désolé mais je dois y aller.' },
  { it: 'Hai un telefono?', fr: 'Avez-vous un téléphone?' },
  { it: 'Qual è il tuo numero?', fr: 'Quel est ton numéro?' },
  { it: 'Il mio numero è...', fr: 'Mon numéro est...' },
  { it: 'Puoi darmi il tuo indirizzo?', fr: 'Peux-tu me donner ton adresse?' },
  { it: 'Ti amo più di ogni cosa.', fr: 'Je t\'aime plus que tout.' },
  { it: 'Sei la mia felicità.', fr: 'Tu es mon bonheur.' },
  { it: 'Non posso vivere senza di te.', fr: 'Je ne peux pas vivre sans toi.' },
  { it: 'Voglio stare con te per sempre.', fr: 'Je veux être avec toi pour toujours.' },
  { it: 'Sarai la mia sposa/sposo?', fr: 'Seras-tu ma fiancée/mon fiancé?' },
  { it: 'Che bella giornata!', fr: 'Quelle belle journée!' },
  { it: 'Il sole brilla.', fr: 'Le soleil brille.' },
  { it: 'Piove oggi.', fr: 'Il pleut aujourd\'hui.' },
  { it: 'Nevica.', fr: 'Il neige.' },
  { it: 'Il vento è forte.', fr: 'Le vent est fort.' },
  { it: 'Qual è la temperatura?', fr: 'Quelle est la température?' },
  { it: 'Fa freddo oggi.', fr: 'Il fait froid aujourd\'hui.' },
  { it: 'Fa caldo oggi.', fr: 'Il fait chaud aujourd\'hui.' },
  { it: 'Che tempo farà domani?', fr: 'Quel temps fera-t-il demain?' },
  { it: 'Secondo le previsioni, pioverà.', fr: 'D\'après les prévisions, il pleuvra.' },
  { it: 'Vorrei un tavolo per due persone.', fr: 'Je voudrais une table pour deux personnes.' },
  { it: 'Avete una tavola disponibile?', fr: 'Avez-vous une table disponible?' },
  { it: 'Qual è il piatto del giorno?', fr: 'Quel est le plat du jour?' },
  { it: 'Mi consiglia qualcosa?', fr: 'Que me recommandez-vous?' },
  { it: 'Vorrei provare la specialità della casa.', fr: 'Je voudrais essayer la spécialité de la maison.' },
  { it: 'È vegetariano?', fr: 'Êtes-vous végétarien?' },
  { it: 'Non mangio carne.', fr: 'Je ne mange pas de viande.' },
  { it: 'Il cibo è delizioso!', fr: 'La nourriture est délicieuse!' },
  { it: 'Potremmo avere il conto, per favore?', fr: 'Pourrait-on avoir l\'addition, s\'il vous plaît?' },
  { it: 'È incluso il servizio?', fr: 'Le service est-il inclus?' },
  { it: 'Grazie per la cena meravigliosa.', fr: 'Merci pour le merveilleux dîner.' },
];

// All irregular verbs
const irregularVerbs = [
  { it: 'Essere', fr: 'Être', passato: 'Stato', pron: '/és-sé-ré/' },
  { it: 'Avere', fr: 'Avoir', passato: 'Avuto', pron: '/a-vé-ré/' },
  { it: 'Andare', fr: 'Aller', passato: 'Andato', pron: '/an-da-ré/' },
  { it: 'Venire', fr: 'Venir', passato: 'Venuto', pron: '/vé-ni-ré/' },
  { it: 'Fare', fr: 'Faire', passato: 'Fatto', pron: '/fa-ré/' },
  { it: 'Dire', fr: 'Dire', passato: 'Detto', pron: '/di-ré/' },
  { it: 'Dare', fr: 'Donner', passato: 'Dato', pron: '/da-ré/' },
  { it: 'Stare', fr: 'Rester/Être', passato: 'Stato', pron: '/sta-ré/' },
  { it: 'Potere', fr: 'Pouvoir', passato: 'Potuto', pron: '/po-té-ré/' },
  { it: 'Dovere', fr: 'Devoir', passato: 'Dovuto', pron: '/do-vé-ré/' },
  { it: 'Volere', fr: 'Vouloir', passato: 'Voluto', pron: '/vo-lé-ré/' },
  { it: 'Sapere', fr: 'Savoir', passato: 'Saputo', pron: '/sa-pé-ré/' },
  { it: 'Rimanere', fr: 'Rester', passato: 'Rimasto', pron: '/ri-ma-né-ré/' },
  { it: 'Bere', fr: 'Boire', passato: 'Bevuto', pron: '/bé-ré/' },
  { it: 'Leggere', fr: 'Lire', passato: 'Letto', pron: '/leg-gé-ré/' },
  { it: 'Scrivere', fr: 'Écrire', passato: 'Scritto', pron: '/skri-vé-ré/' },
  { it: 'Aprire', fr: 'Ouvrir', passato: 'Aperto', pron: '/a-pri-ré/' },
  { it: 'Partire', fr: 'Partir', passato: 'Partito', pron: '/par-ti-ré/' },
  { it: 'Venire', fr: 'Venir', passato: 'Venuto', pron: '/vé-ni-ré/' },
  { it: 'Sentire', fr: 'Entendre', passato: 'Sentito', pron: '/sen-ti-ré/' },
  { it: 'Dormire', fr: 'Dormir', passato: 'Dormito', pron: '/dor-mi-ré/' },
  { it: 'Partire', fr: 'Partir', passato: 'Partito', pron: '/par-ti-ré/' },
  { it: 'Finire', fr: 'Finir', passato: 'Finito', pron: '/fi-ni-ré/' },
  { it: 'Capire', fr: 'Comprendre', passato: 'Capito', pron: '/ka-pi-ré/' },
  { it: 'Costruire', fr: 'Construire', passato: 'Costruito', pron: '/kos-tu-i-ré/' },
  { it: 'Produrre', fr: 'Produire', passato: 'Prodotto', pron: '/pro-dur-ré/' },
  { it: 'Tradurre', fr: 'Traduire', passato: 'Tradotto', pron: '/tra-dur-ré/' },
  { it: 'Introdurre', fr: 'Introduire', passato: 'Introdotto', pron: '/in-tro-dur-ré/' },
  { it: 'Ridurre', fr: 'Réduire', passato: 'Ridotto', pron: '/ri-dur-ré/' },
  { it: 'Portare', fr: 'Porter', passato: 'Portato', pron: '/por-ta-ré/' },
  { it: 'Portare', fr: 'Apporter', passato: 'Portato', pron: '/por-ta-ré/' },
  { it: 'Trovare', fr: 'Trouver', passato: 'Trovato', pron: '/tro-va-ré/' },
  { it: 'Parlare', fr: 'Parler', passato: 'Parlato', pron: '/par-la-ré/' },
  { it: 'Mangiare', fr: 'Manger', passato: 'Mangiato', pron: '/man-ja-ré/' },
  { it: 'Bere', fr: 'Boire', passato: 'Bevuto', pron: '/bé-ré/' },
  { it: 'Correre', fr: 'Courir', passato: 'Corso', pron: '/kor-ré-ré/' },
  { it: 'Spingere', fr: 'Pousser', passato: 'Spinto', pron: '/spín-je-ré/' },
  { it: 'Rompere', fr: 'Casser', passato: 'Rotto', pron: '/rom-pé-ré/' },
  { it: 'Perdere', fr: 'Perdre', passato: 'Perso/Perduto', pron: '/pér-dé-ré/' },
  { it: 'Promettere', fr: 'Promettre', passato: 'Promesso', pron: '/pro-mét-té-ré/' },
  { it: 'Permettere', fr: 'Permettre', passato: 'Permesso', pron: '/per-mét-té-ré/' },
  { it: 'Scommettere', fr: 'Parier', passato: 'Scommesso', pron: '/skom-mét-té-ré/' },
  { it: 'Vivere', fr: 'Vivre', passato: 'Vissuto', pron: '/vi-vé-ré/' },
  { it: 'Soffrire', fr: 'Souffrir', passato: 'Sofferto', pron: '/sof-fri-ré/' },
  { it: 'Offirre', fr: 'Offrir', passato: 'Offerto', pron: '/of-fri-ré/' },
  { it: 'Scoprire', fr: 'Découvrir', passato: 'Scoperto', pron: '/sko-pri-ré/' },
  { it: 'Diventare', fr: 'Devenir', passato: 'Diventato', pron: '/di-ven-ta-ré/' },
  { it: 'Convivere', fr: 'Cohabiter', passato: 'Convissuto', pron: '/kon-vi-vé-ré/' },
  { it: 'Convincere', fr: 'Convaincre', passato: 'Convinto', pron: '/kon-vin-ché-ré/' },
  { it: 'Occorrere', fr: 'Falloir', passato: 'Occorso', pron: '/ok-kor-ré-ré/' },
];

console.log(adjectives.length, 'adjectives');
console.log(usefulAdj.length, 'useful adj');
console.log(phrases100.length, 'phrases');
console.log(irregularVerbs.length, 'irregular verbs');
